name: faces
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.10.0=py314h06a4308_0
  - argon2-cffi=25.1.0=py314h06a4308_0
  - argon2-cffi-bindings=25.1.0=py314hee96239_0
  - asttokens=3.0.0=py314h06a4308_0
  - async-lru=2.0.5=py314h06a4308_0
  - attrs=25.4.0=py314h06a4308_2
  - babel=2.17.0=py314h06a4308_0
  - beautifulsoup4=4.14.2=py314h06a4308_0
  - bleach=6.3.0=py314h06a4308_0
  - brotlicffi=1.2.0.0=py314h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - certifi=2026.01.04=py314h06a4308_0
  - cffi=2.0.0=py314h4eded50_1
  - charset-normalizer=3.4.4=py314h06a4308_0
  - comm=0.2.3=py314h06a4308_0
  - debugpy=1.8.16=py314hbdd6827_1
  - decorator=5.2.1=py314h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=2.2.1=py314h06a4308_0
  - h11=0.16.0=py314h06a4308_1
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py314h06a4308_0
  - httpx=0.28.1=py314h06a4308_1
  - idna=3.11=py314h06a4308_0
  - ipykernel=6.31.0=py314h6fa48dc_0
  - ipython=9.7.0=py314h06a4308_0
  - ipython_pygments_lexers=1.1.1=py314h06a4308_0
  - ipywidgets=8.1.7=py314h06a4308_0
  - jedi=0.19.2=py314h06a4308_0
  - jinja2=3.1.6=py314h06a4308_0
  - json5=0.12.1=py314h06a4308_0
  - jsonschema=4.25.1=py314h06a4308_0
  - jsonschema-specifications=2025.9.1=py314h06a4308_0
  - jupyter=1.1.1=py314h06a4308_0
  - jupyter-lsp=2.3.0=py314h06a4308_0
  - jupyter_client=8.8.0=py314h06a4308_0
  - jupyter_console=6.6.3=py314h06a4308_1
  - jupyter_core=5.9.1=py314h06a4308_0
  - jupyter_events=0.12.0=py314h06a4308_1
  - jupyter_server=2.17.0=py314h06a4308_1
  - jupyter_server_terminals=0.5.3=py314h06a4308_1
  - jupyterlab=4.5.0=py314h06a4308_1
  - jupyterlab_pygments=0.3.0=py314h06a4308_0
  - jupyterlab_server=2.28.0=py314h06a4308_1
  - jupyterlab_widgets=3.0.15=py314h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libmpdec=4.0.0=h5eee18b_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib-inline=0.2.1=py314h06a4308_0
  - mistune=3.1.2=py314h06a4308_0
  - nbclient=0.10.2=py314h06a4308_0
  - nbconvert=7.16.6=py314h06a4308_0
  - nbconvert-core=7.16.6=py314h06a4308_0
  - nbconvert-pandoc=7.16.6=py314h06a4308_0
  - nbformat=5.10.4=py314h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=7.5.0=py314h06a4308_0
  - notebook-shim=0.2.4=py314h06a4308_1
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py314h06a4308_1
  - pandoc=3.8=h06a4308_0
  - pandocfilters=1.5.1=py314h06a4308_0
  - parso=0.8.5=py314h06a4308_0
  - pexpect=4.9.0=py314h06a4308_1
  - pip=25.3=pyh0d26453_0
  - platformdirs=4.5.0=py314h06a4308_0
  - prometheus_client=0.21.1=py314h06a4308_0
  - prompt-toolkit=3.0.52=py314h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py314hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py314h06a4308_0
  - pygments=2.19.2=py314h06a4308_0
  - pysocks=1.7.1=py314h06a4308_1
  - python=3.14.2=h90eec9f_101_cp314
  - python-dateutil=2.9.0post0=py314h06a4308_2
  - python-fastjsonschema=2.21.2=py314h06a4308_0
  - python-json-logger=4.0.0=py314h06a4308_0
  - python_abi=3.14=2_cp314
  - pyyaml=6.0.3=py314h591646f_0
  - pyzmq=27.1.0=py314hcf8288c_1
  - qtconsole=5.7.0=py314h06a4308_0
  - qtpy=2.4.3=py314h06a4308_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py314h06a4308_0
  - requests=2.32.5=py314h06a4308_1
  - rfc3339-validator=0.1.4=py314h06a4308_0
  - rfc3986-validator=0.1.1=py314h06a4308_0
  - rpds-py=0.28.0=py314h498d7c9_0
  - send2trash=1.8.3=py314h06a4308_0
  - six=1.17.0=py314h06a4308_0
  - sniffio=1.3.1=py314h06a4308_0
  - soupsieve=2.5=py314h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - stack_data=0.6.3=py314h06a4308_0
  - terminado=0.18.1=py314h06a4308_1
  - tinycss2=1.4.0=py314h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tornado=6.5.4=py314h47b2149_0
  - traitlets=5.14.3=py314h06a4308_0
  - typing-extensions=4.15.0=py314h06a4308_0
  - typing_extensions=4.15.0=py314h06a4308_0
  - urllib3=2.6.3=py314h06a4308_0
  - wcwidth=0.2.14=py314h06a4308_0
  - webencodings=0.5.1=py314h06a4308_2
  - websocket-client=1.8.0=py314h06a4308_0
  - widgetsnbextension=4.0.14=py314h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - absl-py==2.4.0
      - alembic==1.18.3
      - altair==6.0.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - blinker==1.9.0
      - cachetools==6.2.6
      - choreographer==1.2.1
      - click==8.3.1
      - cloudpickle==3.1.2
      - conformity==1.28.2
      - contourpy==1.3.3
      - cryptography==46.0.4
      - cuda-bindings==13.0.3
      - cuda-pathfinder==1.2.2
      - cycler==0.12.1
      - databricks-sdk==0.82.0
      - docker==7.1.0
      - fastapi==0.128.0
      - filelock==3.20.0
      - flask==3.1.2
      - flask-cors==6.0.2
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fsspec==2025.12.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.48.0
      - graphene==3.4.3
      - graphql-core==3.2.7
      - graphql-relay==3.2.0
      - greenlet==3.3.1
      - gunicorn==23.0.0
      - huey==2.6.0
      - importlib-metadata==8.7.1
      - iniconfig==2.3.0
      - itsdangerous==2.2.0
      - joblib==1.5.3
      - kaleido==1.2.0
      - kiwisolver==1.4.9
      - lightning-utilities==0.15.2
      - logistro==2.0.1
      - mako==1.3.10
      - markupsafe==2.1.5
      - matplotlib==3.10.8
      - mediapipe==0.10.32
      - mlflow==3.9.0
      - mlflow-skinny==3.9.0
      - mlflow-tracing==3.9.0
      - mpmath==1.3.0
      - narwhals==2.15.0
      - networkx==3.6.1
      - numpy==2.3.5
      - nvidia-cublas==13.1.0.3
      - nvidia-cuda-cupti==13.0.85
      - nvidia-cuda-nvrtc==13.0.88
      - nvidia-cuda-runtime==13.0.96
      - nvidia-cudnn-cu13==9.15.1.9
      - nvidia-cufft==12.0.0.61
      - nvidia-cufile==1.15.1.6
      - nvidia-curand==10.4.0.35
      - nvidia-cusolver==12.0.4.66
      - nvidia-cusparse==12.6.3.3
      - nvidia-cusparselt-cu13==0.8.0
      - nvidia-nccl-cu13==2.28.9
      - nvidia-nvjitlink==13.0.88
      - nvidia-nvshmem-cu13==3.4.5
      - nvidia-nvtx==13.0.85
      - opencv-contrib-python==4.13.0.90
      - opentelemetry-api==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - orjson==3.11.7
      - pandas==2.3.3
      - patsy==1.0.2
      - pillow==12.0.0
      - plotly==6.5.2
      - pluggy==1.6.0
      - polars==1.37.1
      - polars-runtime-32==1.37.1
      - prettytable==3.17.0
      - protobuf==6.33.5
      - pyarrow==22.0.0
      - pyasn1==0.6.2
      - pyasn1-modules==0.4.2
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydeck==0.9.1
      - pymetrics==1.0.10
      - pyparsing==3.3.2
      - pytest==9.0.2
      - pytest-timeout==2.4.0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - rsa==4.9.1
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - setuptools==70.2.0
      - simplejson==3.20.2
      - skops==0.13.0
      - smmap==5.0.2
      - sounddevice==0.5.5
      - sqlalchemy==2.0.46
      - sqlparse==0.5.5
      - starlette==0.50.0
      - statsmodels==0.14.6
      - streamlit==1.54.0
      - sympy==1.14.0
      - tabulate==0.9.0
      - tenacity==9.1.3
      - threadpoolctl==3.6.0
      - toml==0.10.2
      - torch==2.10.0+cu130
      - torchmetrics==1.8.2
      - torchvision==0.25.0+cu130
      - tqdm==4.67.2
      - triton==3.6.0
      - typing-inspection==0.4.2
      - tzdata==2025.3
      - uvicorn==0.40.0
      - watchdog==6.0.0
      - werkzeug==3.1.5
      - zipp==3.23.0
prefix: /home/dxd/anaconda3/envs/faces
